eco-api/src/main/kotlin/com/willfp/libreforge/effects/effects/EffectIgnite.kt, eco-api/src/main/kotlin/com/willfp/libreforge/triggers/Trigger.kt
Added "antigrief-check: true/false" parameter to every victimable trigger. 
Added "send-cooldown-message: true/false" (true by default) parameter to every cooldownable trigger. 
Added Ignite effect with "ticks: int" and "damage-per-tick: double" parmeters to burn victim.
=> 2 global trigger parameters and a new efect

eco-api/src/main/kotlin/com/willfp/libreforge/effects/effects/EffectMineRadius.kt
`mine_radius` during `check_hardness` was ignoring whether the block was unbreakable or not.
Adjusted it just by checking if type hardness is -1
https://github.com/Auxilor/EcoEnchants/issues/324
=> made `check_hardness` check if block's unbreakable

eco-api/src/main/kotlin/com/willfp/libreforge/triggers/triggers/TriggerAltClick.kt
Now alt_click trigger won't trigger if you activate a pressure plate or a tripwire hook, or when you step on a redstone ore or soil
=> 🐛 bug: made alt_click trigger ignore `Action.PHYSICAL`

eco-api/src/main/kotlin/com/willfp/libreforge/effects/effects/EffectKeepInventory.kt
In world without keepInventory gamerule, players will still drop inventory items, but the inventory was not cleaned, so players will get double inventory items when they death, this PR is fixing this problem.
=> Fixed keepInventory effect still drop players item.

eco-api/src/main/kotlin/com/willfp/libreforge/triggers/triggers/TriggerCraft.kt
Currently the "craft" trigger does not differentiate between crafting one item and an entire stack via shift-clicking. 
This meant that if an EcoSkills skill gains experience from crafting, for example, then players are rewarded by clicking to craft a recipe over and over, one result at a time, instead of shift-clicking to craft the whole stack... because shift-clicking still returned the 1.0 value.
I've modified TriggerCraft to return the number of repetitions of the recipe crafted. Spigot doesn't directly support this, so we have to check the player's inventory capacity to calculate the number that actually get crafted.
In the process of adding this feature, I also came across several edge cases where TriggerCraft would fire despite no item actually being crafted. Those loopholes would …
=> TriggerCraft returns repetitions on shift-click, fixes edge cases.

core/src/main/kotlin/com/willfp/libreforge/HolderUpdates.kt, core/src/main/kotlin/com/willfp/libreforge/effects/ElementLike.kt, core/src/main/kotlin/com/willfp/libreforge/effects/arguments/impl/ArgumentEvery.kt
- calculate repeat and delay args only if needed to save some cpu time
tests (/spark profiler --timeout 30):
spark without commit: https://spark.lucko.me/8ZjnqIXmD1 (2464 ms) 
spark with commit applied: https://spark.lucko.me/T5mz0tTQ8F (1544 ms)
- fix every argument to not return true on first check
=> Optimization and some fixes

core/src/main/kotlin/com/willfp/libreforge/conditions/impl/ConditionPlaceholderContains.kt, core/src/main/kotlin/com/willfp/libreforge/conditions/impl/ConditionPlaceholderEquals.kt
This also adds the "ignore_case" option for placeholder_equals to ensure consistency.
=> Parse placeholders in value for `placeholder_equals` and `placeholder_contains` conditions.

core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectAOE.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectAgeCrop.kt
Currently AOE isn't working as it should.
the TriggerData being used to run is only getting the "victim" from the trigger, which there is only one from the triggers. Instead of getting the entity which is from the return list of the shapes.
This fixes it, but is kinda scuffed.
=> Scuffed fix for AOE

core/src/main/kotlin/com/willfp/libreforge/effects/Effects.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectSetArmorTrim.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectVictimMovementMultiplier.kt
This apply to mobs and players, the movement_multiplier currently only apply to players.
example config might look like this:
```
effects:
- id: victim_movement_multiplier
args:
multiplier: 0.5
duration: 60 # optional, duration for the effect to last in ticks
triggers:
- melee_attack
```
=> Add victim_movement_multiplier

core/src/main/kotlin/com/willfp/libreforge/effects/Effects.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectGiveFood.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectGiveSaturation.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectSetFood.kt, core/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectSetSaturation.kt
Okay - this is take two (see #118) and I've confirmed it works in game.
I would love to build on this and add a system similar to how vanilla saturation works, where the max saturation you can receive is your current hunger/food value, but that's a little beyond my just-downloaded-inteliiJ-today skills.
```
- id: give_saturation
args:
amount: 1 # The amount of saturation to give/take (allows negative values)
```
=> expand hunger effects (add give_saturation, set_food, set_saturation) (respect-vanilla-limits for give_food + give_saturation)

core/build.gradle.kts, core/src/main/kotlin/com/willfp/libreforge/LibreforgeSpigotPlugin.kt, core/src/main/kotlin/com/willfp/libreforge/integrations/auraskills/AuraSkillsIntegration.kt, core/src/main/kotlin/com/willfp/libreforge/integrations/auraskills/impl/ArgumentManaCost.kt, core/src/main/kotlin/com/willfp/libreforge/integrations/auraskills/impl/ConditionHasMana.kt, core/src/main/kotlin/com/willfp/libreforge/integrations/auraskills/impl/EffectAddStat.kt, core/src/main/kotlin/com/willfp/libreforge/integrations/auraskills/impl/EffectSkillXpMultiplier.kt
This PR adds support for AuraSkills 2.0 (formerly AureliumSkills). 2.0 has a completely new API with separate packages and a different plugin name so the old AureliumSkills integration can still exist at the same time and work for users using AureliumSkills. I haven't tested if this fully works but I just based it off the existing AureliumSkills integration, so let me know if I missed anything.
[2.0 API docs if needed](https://wiki.aurelium.dev/auraskills/api)
=> Add AuraSkills 2.0 integration

core/src/main/kotlin/com/willfp/libreforge/triggers/impl/TriggerCraft.kt
Thanks to @Exanthiax for recommendation.
=> Updated craft trigger to return total items crafted.

core/src/main/kotlin/com/willfp/libreforge/conditions/impl/ConditionNearEntity.kt
example:
```YAML
enabled: true
effects:
- id: send_message
args:
message: "At least 2 zombies"
triggers:
- click_entity
conditions:
- id: near_entity
args:
radius: 10
entities:
- Zombie
amount: 2
```
=> Added optional 'amount' (minimum entities matched) arg to 'near_entity'.

core/src/main/kotlin/com/willfp/libreforge/effects/templates/AttributeEffect.kt
Attributes not properly removing on version < 1.21, because of random UUID
=> fix attributes on version < 1.21

core/common/src/main/kotlin/com/willfp/libreforge/filters/Filters.kt, core/common/src/main/kotlin/com/willfp/libreforge/filters/impl/FilterSpawnerEntity.kt
Added `spawner_entity` filter. This is to be used with a mine_block trigger to only action when a spawner of x entity type was mined.
=> added spawner entity filter

core/common/src/main/kotlin/com/willfp/libreforge/HolderUpdates.kt, core/common/src/main/resources/config.yml
Optionally disable holder updates for item pickup events.
Relevant spark report sent by someone on Discord: https://spark.lucko.me/ZHLJzWdiTK
1. For example on my server, I will only use Pets and Talismans. There is no reason for this to refresh anything since talismans will only work in the Talismans inventory.
2. Optionally disabling something that will fix itself instantly when you do anything in your inventory is fine IMO if the result prevents the server from crashing by some dumb mob farm players.
=> Added ability to disable holder update on item pickup

core/common/src/main/kotlin/com/willfp/libreforge/triggers/impl/TriggerHeadshot.kt
For my quests in EcoQuests I added abilty to filter projectiles, that can be used in headshot trigger. 
To test it you can use this simple task in quest:
```
description: "&fMake headshot by arrow (&a%xp%&8/&a%required-xp%&f)"
xp-gain-methods:
- trigger: headshot
value: 1
filters:
projectiles:
- arrow
```
=> FEAT: Added ability to use `projectile` filter with `headshot` trigger

loader/src/main/kotlin/com/willfp/libreforge/loader/internal/LibreforgeLoader.kt
At present, nobody can really use custom libreforge forks with multiple eco plugins. This PR fixes this issue by preventing the eco plugins from force-loading libreforge multiple times. 
I would like to disable/improve a lot of holder updates and make changes to the other eco plugins as well to optimize the hell out of them and remove the refreshes I don't need, or to make the entire effect system semi async maybe. I need to test it with almost every eco plugin if I ever want to merge this back (though I highly doubt you would accept something like this).
Will be much easier if this would just work and I wouldn't need to patch every eco plugin individually, to properly force load custom versions of libreforge.
=> Fix force loading of libreforge.jar multiple times

core/common/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectDamageNearbyEntities.kt, core/common/src/main/kotlin/com/willfp/libreforge/triggers/impl/TriggerMeleeAttack.kt
Fixes #186
Add checks to prevent recursive damage triggering and event handling to resolve memory leak issue.
* **EffectDamageNearbyEntities.kt**:
- Add a `Set<UUID>` to track damaged entities.
- Modify the `onTrigger` method to include a check for recursive damage.
- Clear the `Set<UUID>` after processing all entities to avoid memory leaks.
* **TriggerMeleeAttack.kt**:
- Add a `Set<UUID>` to track processed events.
- Modify the `handle` method to include a check for recursive event handling.
- Clear the `Set<UUID>` after processing the event to avoid memory leaks.
=> Fix memory leak issue causing StackOverflowError

core/common/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectBroadcast.kt, core/common/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectRunCommand.kt, core/common/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectRunPlayerCommand.kt, core/common/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectSendMessage.kt, core/common/src/main/kotlin/com/willfp/libreforge/integrations/paper/impl/EffectSendMinimessage.kt
Currently, 'send_message' & 'broadcast' add a blank line message at the end when using plural key (messages). The 'run_command' and 'run_player_command' also run a blank command on every trigger, which in some cases produces a libreforge error.
This PR fixes all of the above and it is now much cleaner to use.
=> fixed additional blank line

core/common/src/main/kotlin/com/willfp/libreforge/Weighted.kt
This fixes two issues with weighted chains in the latest version:
1. If you don't specify a weight.. "List is Empty". If none is specified then it should be equal weights. This is resolved.
2. Weights don't actually do anything... I had a list of 10,20,50 and 90. They all still came randomly. This also fixed this.
Feel free to tidy it up, but this is working for me currrently.
=> Fixed weighted chains

core/common/src/main/kotlin/com/willfp/libreforge/conditions/impl/ConditionPlaceholderGreaterThan.kt, core/common/src/main/kotlin/com/willfp/libreforge/conditions/impl/ConditionPlaceholderLessThan.kt
Firstly, in the wiki (https://plugins.auxilor.io/effects/all-conditions/placeholder_greater_than) it says "greater than or equal" for `placeholder_higher_than` condition, which it's not actually the case as the operator is `>` and not `>=`.
Secondly, it should be a mathematical evaluation, not a formatted string followed by a conversion to double. Probably this is why in most cases, those 2 conditions don't work accordingly with placeholders, if any space, or character, or whatever is present.
Thirdly, allow placeholders to be evaluated in both `placeholder` and `value` arguments.
=> Fix those damn placeholder conditions

core/common/src/main/kotlin/com/willfp/libreforge/effects/impl/EffectPlaySound.kt
This PR adds a `category` config option that allows users to put in their own category that's not MASTER. This is an optional config option and will default to MASTER when none is present, preserving existing behavior on servers while still adding now functionality to servers who wish to use it.
=> Add Sound Category as Configurable Option to Play Sound Effect
